### ISSUE TITLE
_this.$sleep is not a function

### ISSUE THREAD

**Issue by KazakovKirill** [acidjazz/tv-modal#1]
When using modal I'm getting this error:
"__this.$sleep is not a function_"

It caused by:
```
await this.$sleep(100)
```
in **GlobalModal.vue**

**Comment by acidjazz** [comment]
Sorry @KazakovKirill thats from another package, removing that now.

**Comment by acidjazz** [comment]
@KazakovKirill fixed in [v1.0.4](https://github.com/acidjazz/tv-modal/releases/tag/v1.0.4)

**Comment by KazakovKirill** [comment]
Still not fixed in 1.0.4:
**GlobalModal.vue**
Lines: 93, 99, 107
