### ISSUE TITLE
Modal animation missing on modal close

### ISSUE THREAD

**Issue by KazakovKirill** [acidjazz/tv-modal#3]
Everything ok with open animation,
but closing animation missing.

I took code from this example:
```
this.$modal.show({
    type: 'danger',
    title: 'This is the title property',
    body: 'This is the body property.  Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eius aliquam laudantium explicabo pariatur iste dolorem animi vitae error totam.',
    primary: {
      label: 'Primary Action',
      theme: 'red',
      action: () => this.$toast.success('Primary Button clicked'),
    },
    secondary: {
      label: 'Secondary Button',
      theme: 'white',
      action: () => this.$toast.info('Clicked Secondary'),
    },
  })
```

I'm expecting closing animation as on this preview:
https://github.com/acidjazz/tv-modal/raw/master/media/example1.gif

**Comment by acidjazz** [comment]
@KazakovKirill try using the component via [nuxt-tailvue](https://github.com/acidjazz/nuxt-tailvue)

check out the kitchen sink i placed in https://github.com/acidjazz/laranuxt . get that going locally and youll see how its used

**Comment by KazakovKirill** [comment]
As I wrote in previous comment I'm using 'nuxt-tailvue'

My **nuxt.config.js**
```
modules: [
  ['nuxt-tailvue', { all: true }],
]
```

Please check this repo:
https://github.com/KazakovKirill/tv-modal-demo

After setting up clean nuxt project using 
```
yarn create nuxt-app
```
picking tailwind option there and then installing a nuxt-tailvue package I'm gettting "**_this.$sleep is not a function error**" error after modal closed, but closing animation is present.

Then after replace **this.$sleep()** with **setTimeout()** in **GlobalModal.vue** and **ModalBase.vue** error gone, but modal closing animation is missing
```
// await this.$sleep(200)
await setTimeout(null, 200)
```

**Comment by acidjazz** [comment]
@KazakovKirill appreciate your patience and detail, sleep/timeout is needed to ensure the exit animation fires. i've updated nuxt-tailvue to include that helper. upgrade nuxt-tailvue and you should be fine

My fork/PR has the fix as well https://github.com/acidjazz/tv-modal-demo

**Comment by acidjazz** [comment]
@KazakovKirill just double checking to see if upgrading fixed this
